apiVersion: v1
kind: Pod
metadata:
  name: app-pod
  namespace: webapp
spec:
  containers:
    - name: app-container
      image: 708519571347.dkr.ecr.us-east-1.amazonaws.com/ecr1:v0.1
      ports:
        - containerPort: 8080
      env:
        - name: DBHOST
          value: mysql-service.sqldb
        - name: DBPORT
          value: "3306"
        - name: DBUSER
          value: root
        - name: DBPWD
          value: pw
        - name: DATABASE
          value: employees
        - name: APP_COLOR
          value: blue
