apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: app-container-rs
  namespace: webapp
  labels:
    app: employees
    version: v1
spec:
  replicas: 6
  selector:
    matchLabels:
      app: employees
      version: v1
  template:
    metadata:
      labels:
        app: employees
        version: v1
    spec:
      containers:
        - name: app-container
          image: 708519571347.dkr.ecr.us-east-1.amazonaws.com/ecr1:v0.1
          ports:
            - containerPort: 8080
          env:
            - name: DBHOST
              value: mysql-service.sqldb
            - name: DBPORT
              value: "3306"
            - name: DBUSER
              value: root
            - name: DBPWD
              value: pw
