apiVersion: v1
kind: Service
metadata:
  name: app-container-service
  namespace: webapp
spec:
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30008
  selector:
    app: employees
    version: v1
  type: NodePort
