apiVersion: v1
kind: Pod
metadata:
  name: mysql-pod2
  namespace: sqldb
  labels:
    app: mysql-pod
spec:
  containers:
    - name: mysql-container
      image: 708519571347.dkr.ecr.us-east-1.amazonaws.com/ecr2:db-v0.1
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: pw
      ports:
        - containerPort: 3306
