apiVersion: v1
kind: Pod
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Pod","metadata":{"annotations":{},"name":"mysql-pod","namespace":"sqldb"},"spec":{"containers":[{"env":[{"name":"MYSQL_ROOT_PASSWORD","value":"pw"}],"image":"708519571347.dkr.ecr.us-east-1.amazonaws.com/ecr2:db-v0.1","name":"mysql-container","ports":[{"containerPort":3306}]}]}}
  creationTimestamp: "2023-07-05T22:49:57Z"
  name: mysql-pod
  namespace: sqldb
  resourceVersion: "155486"
  selfLink: /api/v1/namespaces/sqldb/pods/mysql-pod
  uid: 52af6ee4-1f06-48de-adda-08b9fa381768
spec:
  containers:
  - env:
    - name: MYSQL_ROOT_PASSWORD
      value: pw
    image: 708519571347.dkr.ecr.us-east-1.amazonaws.com/ecr2:db-v0.1
    imagePullPolicy: IfNotPresent
    name: mysql-container
    ports:
    - containerPort: 3306
      protocol: TCP
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: default-token-wm45k
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: kind-control-plane
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: default-token-wm45k
    secret:
      defaultMode: 420
      secretName: default-token-wm45k
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2023-07-05T22:49:57Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2023-07-05T22:50:15Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2023-07-05T22:50:15Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2023-07-05T22:49:57Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: containerd://75f2752e2be4e6e1db63736c837ba522ce05511c1d836c81df36742dfa29da4a
    image: 708519571347.dkr.ecr.us-east-1.amazonaws.com/ecr2:db-v0.1
    imageID: 708519571347.dkr.ecr.us-east-1.amazonaws.com/ecr2@sha256:f3be78e93d05a8dd91fa6dba83001491c5f081c6128a6239e300f2bf7f13c7f5
    lastState: {}
    name: mysql-container
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2023-07-05T22:50:14Z"
  hostIP: 172.18.0.2
  phase: Running
  podIP: 10.244.0.26
  podIPs:
  - ip: 10.244.0.26
  qosClass: BestEffort
  startTime: "2023-07-05T22:49:57Z"
